# serverless.yml

# PRODUCTION MODE -----------------------------------
# name: CiergioAdmintool

# ociNextApp:
#   component: "@sls-next/serverless-component@1.19.0-alpha.35"
#   inputs:
#     runtime: "nodejs12.x"
#     domain: ["admin","ciergiopray.com"]
#     domainType: "both"
#     memory: 1024
#     cloudfront:
#       api/*:
#         forward:
#           headers: [Host]

# TEST MODE -----------------------------------

name: CiergioTestAdmintool

ociNextApp:
  component: "@sls-next/serverless-component@3.6.0"
  inputs:
    runtime: "nodejs14.x"
    domain: ["test","ciergiopray.com"]
    domainType: "both"
    memory: 1024
    cloudfront:
      api/*:
        forward:
          headers: [Host]



# -------------------- UNUSED ----
    # publicDirectoryCache:
    #   value: public, max-age=604800
    #   test: /\.(gif|jpe?g|png|txt|xml)$/i